### ISSUE TITLE
circular dependencies making knip stuck

### ISSUE THREAD

**Issue by blephy** [webpro-nl/knip#749] opened 2024-08-06 10:52 UTC
### Reproduction url

https://github.com/blephy/knip-circulare-dep

### Description of the issue

Given a mono-repository, if it's contains project which are dependent on each other, knip is running in loop and never failed.

Yes, circular dependencies are bad, but there is some case you cannot do anything about : 

- a prettier-config project
- an eslint-config project

Each are requesting each other.

I did manage to bypass this bug by not including in their package.json's devDependencies the package, but instead to rely on a relative import in configs.

instead of : 

```json
{
  "name": "prettier-config",
  "devDependencies": {
    "eslint-config": "workspace: *"
  }
}
```

and

```js
module.exports = {
  root: true,
  extends: ['eslint-config'],
};
```

do : 

```json
{
  "name": "prettier-config",
  "devDependencies": {
  }
}
```

and

```js
module.exports = {
  root: true,
  extends: ['../eslint-config/index.cjs'],
};
```

**Comment by webpro** [comment] 2024-08-06 10:54
> https://i-do-no-have.com/

it-is-required.though

**Comment by blephy** [comment] 2024-08-06 10:56
> > https://i-do-no-have.com/
> 
> it-is-required.though

I will make it in a couple of hours. Sorry i do not have time right now

**Comment by blephy** [comment] 2024-08-06 12:04
cc @webpro 

https://github.com/blephy/knip-circulare-dep

**Comment by webpro** [comment] 2024-08-07 05:06
No issues here:

```
❯ pnpm knip

> root@1.0.0 knip /Users/lars/p/knip/exercises/knip-circulare-dep
> VITE_CJS_IGNORE_WARNING=true knip

Unused devDependencies (2)
eslint-config  libs/prettier-config/package.json
nx             package.json
Unlisted dependencies (1)
eslint-config-eslint-config  libs/prettier-config/.eslintrc.cjs
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by blephy** [comment] 2024-08-07 12:33
Hum ...

is it relative to Node / OS ? 

i'm on 

```shell
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
```

**Comment by webpro** [comment] 2024-08-07 14:23
You could try CSB or SB: https://knip.dev/guides/issue-reproduction#templates

**Comment by webpro** [comment] 2024-09-21 05:31
Closing this due to unable to reproduce.

**Closed by webpro** 2024-09-21 05:31 UTC
Labels: bug
