### ISSUE TITLE
Conditional required import not longer working

### ISSUE THREAD

**Issue by eppisapiafsl** [webpro-nl/knip#744] opened 2024-07-29 14:54 UTC
### Reproduction url

https://github.com/eppisapiafsl/KnipIssues

### Reproduction url

5.26

### Reproduction url

5.27

### Description of the regression

Before

Knip recognized the files that were conditionally imported either by Jest configuration or in the "dev" environment  via `require(...)` 

After the upgrade to 5.27, Knip starts reporting unused files that are imported via the `required` method that is inside function or a `if` condition 

Example, Reactroton config and Jest Setup

```
if (__DEV__ && !process.env.JEST_WORKER_ID) {
  require("./ReactotronConfig");
}


// Jest.setup.ts
jest.mock("react-native-twilio-video-webrtc", () => {
  const {
    ForwardedTwilioVideoMock,
    TwilioVideoLocalViewMock,
    TwilioVideoParticipantViewMock,
  } = require("./src/commons/Utils/TestMocks/MockTwilioVideo.tsx");

  return {
    TwilioVideo: ForwardedTwilioVideoMock,
    TwilioVideoLocalView: TwilioVideoLocalViewMock,
    TwilioVideoParticipantView: TwilioVideoParticipantViewMock,
  };
});
```

I was able to reproduce the Reactotron issue; it's available in the public repo https://github.com/eppisapiafsl/KnipIssues

Once in the main branch, install the dependencies `npm install` and run `npm run deadcode`

<img width="981" alt="Screenshot 2024-07-29 at 10 53 35" src="https://github.com/user-attachments/assets/ffa09dbc-691c-4d14-93ec-81c99af37d19">

**Comment by webpro** [comment] 2024-07-30 05:45
This doesn't look like a very minimal reproduction. And if I do `npm start deadcode` it starts a development server.

**Comment by webpro** [comment] 2024-07-30 06:13
Typo? `ReactrotonConfig` !== `ReactotronConfig`

**Comment by eppisapiafsl** [comment] 2024-07-30 14:02
👋 @webpro I updated the repo setting and fixed the typo

You can run `npx knip`, the file `ReactotronConfig` is reported as unused

**Comment by webpro** [comment] 2024-07-30 14:26
Oh wait, you are requiring a ts file. That's "broken" since a while, also see #681

**Comment by eppisapiafsl** [comment] 2024-07-30 23:10
@webpro Yeah.... this fix didn't work in my case https://github.com/webpro-nl/knip/issues/681#issuecomment-2182798525 

It was working fine with Knip 5.26 😅

**Comment by webpro** [comment] 2024-07-31 06:00
> It was working fine with Knip 5.26 😅

Are you sure? I think it still reports `src/ReactotronConfig.ts` as unused.

This is non-standard usage (e.g. if you option-click in VS Code you can see it's not going anywhere), probably handled by Metro (which has a custom module resolver).

Might be fixable though, stay tuned.

**Comment by webpro** [comment] 2024-07-31 08:42
Feel free to try `npm i -D https://pkg.pr.new/knip@3d5a536`, we might be on to something :)

**Comment by eppisapiafsl** [comment] 2024-07-31 16:20
@webpro 

> Are you sure? I think it still reports src/ReactotronConfig.ts as unused.

💯 , I try to keep knip in the latest version in my repo

> Feel free to try npm i -D https://pkg.pr.new/knip@3d5a536, we might be on to something :)

This package work as expected, I don't get the report with that version
<img width="708" alt="Screenshot 2024-07-31 at 12 18 54" src="https://github.com/user-attachments/assets/832dc3ef-dc9a-4268-b356-4f9a58a621d2">

**Comment by webpro** [comment] 2024-08-01 05:57
Thanks for confirming this! Should be in the next version.

**Comment by webpro** [comment] 2024-08-07 05:49
It's in 5.27.1, so closing this one.

**Closed by webpro** 2024-08-07 05:49 UTC
Labels: regression
