### ISSUE TITLE
Umm... name may be offensive to Japanese people

### ISSUE THREAD

**Issue by thesunny** [webpro-nl/knip#758] opened 2024-08-16 19:11 UTC
First of all, love what this tool does. Was looking for something like this for a long time.

I'm not a precious butterfly or anything, but "nip" is a derogatory term for Japanese people (I'm Japanese, born in Canada). I know it's not intended to be used offensively, but every time the word nip was used in the video, I involuntarily cringed. Think of it as the "n" word for Japanese people. I heard it sometimes while growing up.

Here's what Chat GPT says about the word when asked:

> The term “nip” has been used as a derogatory slur, particularly during the World War II era, to refer to Japanese people. The word is a shortening of “Nippon,” which is the Japanese word for Japan. During the war, this term was used by Allied forces, especially in Western countries, as a racial slur to dehumanize and demean the Japanese, reflecting the intense animosity and racism of the time.
>
> Using “nip” as a slur carries significant historical weight and is considered offensive because of its association with that period and the derogatory connotations it acquired. It’s important to recognize the hurtful impact such terms can have, particularly on those of Japanese descent, and to avoid their use in any context that might perpetuate harm or reinforce negative stereotypes.

**Comment by webpro** [comment] 2024-08-17 12:16
Sounds like the issue is not in the name, but the pronunciation. The name is Dutch, and the "k" is literally and clearly pronounced at the start of the word (just like the "c" in "cut"). People not pronouncing the "k" is unfortunate.

**Comment by thesunny** [comment] 2024-08-18 04:20
Please note that the introductory video on the homepage of the knip.dev website pronounces it with an "n" repeatedly.

It's a good video. Not sure what the options are or if there are any. This is more of a heads up.

Good luck with the project and thanks for sharing it with the community

**Comment by webpro** [comment] 2024-08-18 07:54
Thanks, I do appreciate you mentioning this. I'm sorry you felt that way listening to the video. Hopefully it's a thing of the past and the association will fade.

Before I had this information I didn't really mind people mispronouncing Knip. From now on, I will try to steer pronunciation in the right direction whenever I can.

Also, thanks for the kind words!

**Comment by webpro** [comment] 2024-08-19 07:32
Added meaning/pronunciation/origin hints in two places:

- https://knip.dev
- https://github.com/webpro-nl/knip

With this, I'm going to close this issue.

**Closed by webpro** 2024-08-19 07:32 UTC
Labels: discussion
