### ISSUE TITLE
WebWorker not detected as being used

### ISSUE THREAD

**Issue by gregberge** [webpro-nl/knip#686] opened 2024-06-18 20:26 UTC
I use Vite and I created a WebWorker, it's not detected as a deps.

**My code**
```ts
const worker = new Worker(new URL("./worker.ts", import.meta.url));
```

**Knip output**
```
Unused files (1)
apps/frontend/src/util/color-detection/worker.ts
```

See here: https://github.com/argos-ci/argos/actions/runs/9571665801/job/26389276724?pr=1334

**Comment by webpro** [comment] 2024-06-18 21:02
Is this a regression or a feature request?

**Comment by webpro** [comment] 2024-06-18 21:03
Sounds like a duplicate of #237. See my comment at the end, so unfortunately have to close this one as well.

**Closed by webpro** 2024-06-18 21:03 UTC
Labels: bug
