### ISSUE TITLE
default exported object does not track usage

### ISSUE THREAD

**Issue by vitalyiegorov** [webpro-nl/knip#721] opened 2024-07-09 10:37 UTC
Old Apollo server code can have such resolvers declarations:

- `my.args.ts`
```ts
export interface MyArgs {
 id: string;
}
```

- `my.query.ts`
```ts
import type { MyArgs } from './my.args.ts'

export default {
    Query: {
        async myQuery(root: unknown, args: MyArgs, context: unknown) {
            return  []
        },
    },
}
```

Knip does not see the usage in the `export default` block and reports `MyAgrs` type as `Unused exported types`

**Comment by webpro** [comment] 2024-07-09 10:48
Please provide full reproduction. Looks like code is invalid:

```
export type MyArgs = {}
```

**Comment by vitalyiegorov** [comment] 2024-07-10 10:36
it was a typo, fixed the initial message, the problem is with this construct:
```ts
export default { ... }
```

**Comment by webpro** [comment] 2024-07-11 07:32
From opening an issue and my comment it should be clear that a reproduction is desired.

Still, I took the time to copy paste your code into files myself only to find out the report is invalid:

```
$ cat my.args.ts 
export interface MyArgs {
  id: string;
}
$ cat my.query.ts 
import type { MyArgs } from './my.args.ts';

export default {
  Query: {
    async myQuery(root: unknown, args: MyArgs, context: unknown) {
      return [];
    },
  },
};
$ cat index.ts 
import d from './my.query.ts';
d;
$ knip
✂️  Excellent, Knip found no issues.
$ 
```

Therefore I'm going to close this issue.

**Closed by webpro** 2024-07-11 07:32 UTC
Labels: bug
