### ISSUE TITLE
@types/xxx dependencies reported as unused

### ISSUE THREAD

**Issue by guillaumebrunerie** [webpro-nl/knip#753] opened 2024-08-09 14:58 UTC
### Reproduction url

N/A

### Description of the issue

I’m using some NPM packages to the get the types for various experimental APIs, but Knip reports them as being unused. Am I supposed to do something special for them to be recognized?

```
$ npx knip
Analyzing workspace ....
Unused devDependencies (3)
@types/webpack-env                  package.json
@types/webscreens-window-placement  package.json
@types/wicg-file-system-access      package.json
```

For instance `@types/wicg-file-system-access` simply adds functions in the global scope like `showDirectoryPicker` with the appropriate type, but the package is never explicitly mentioned anywhere in my code.

**Comment by webpro** [comment] 2024-08-14 09:14
> the package is never explicitly mentioned anywhere in my code.

There's your answer.

Can't say much without a reproduction, that field is there for a reason. Using `--debug` reveals more.

**Comment by guillaumebrunerie** [comment] 2024-08-14 10:20
I managed to fix it by adding some `/// <reference types="webscreens-window-placement" />` directives in a `globals.d.ts` file in my project, even though it is not required by Typescript (by default Typescript considers all types defined in `@types/*` packages to be visible).

I guess it makes sense to have explicit references to those packages in my code. Alternatively, Knip would need to never report `@types/*` packages as unused, as the types defined there can potentially be used without any import.

**Comment by webpro** [comment] 2024-08-14 10:26
> Alternatively, Knip would need to never report `@types/*` packages as unused, as the types defined there can potentially be used without any import.

That would default the purpose of Knip. TypeScript does not use all such packages by default (nor should it). Knip tries to follow up on what TypeScript loads, but there might definitely be gaps: https://github.com/webpro-nl/knip/blob/4f19785770686d79a6826fab372bc8ebf0edf522/packages/knip/src/util/tsconfig-loader.ts#L12

However, you seem unwilling to provide a reproduction so let's just close this one.

**Closed by webpro** 2024-08-14 10:26 UTC
Labels: bug

**Comment by guillaumebrunerie** [comment] 2024-08-14 11:24
> > Alternatively, Knip would need to never report `@types/*` packages as unused, as the types defined there can potentially be used without any import.
> 
> That would defeat the purpose of Knip. TypeScript does not use all such packages by default (nor should it). Knip tries to follow up on what TypeScript loads, but there might definitely be gaps:
> 
> https://github.com/webpro-nl/knip/blob/4f19785770686d79a6826fab372bc8ebf0edf522/packages/knip/src/util/tsconfig-loader.ts#L12

This is incorrect, Typescript absolutely does use such packages by default. See for instance the documentation at https://www.typescriptlang.org/tsconfig/#types:

> By default all visible ”@types” packages are included in your compilation. Packages in node_modules/@types of any enclosing folder are considered visible. For example, that means packages within ./node_modules/@types/, ../node_modules/@types/, ../../node_modules/@types/, and so on.

> However, you seem unwilling to provide a reproduction so let's just close this one.

Here is a reproduction: https://github.com/guillaumebrunerie/knip-types-test
It is simply a default Vite project where I added a call to `showDirectoryPicker` in `main.ts`.

Note that Knip complains about an unused devDependency:
```
Unused devDependencies (1)
@types/wicg-file-system-access  package.json
```
while Typescript finds no issues (`npx tsc`).

But if you remove the dependency to make Knip happy, Typescript will complain:
```
src/main.ts:25:1 - error TS2304: Cannot find name 'showDirectoryPicker'.

25 showDirectoryPicker()
   ~~~~~~~~~~~~~~~~~~~


Found 1 error in src/main.ts:25
```

**Comment by webpro** [comment] 2024-08-21 06:34
> Typescript absolutely does use such packages by default. 

You're right. We look at this differently, because when I use TypeScript APIs to read and parse the configuration at `tsconfig.json` the definition's not there and also it isn't requested by the module resolver.

I've had kind of a similar issue before in #206 where `tsc` implicitly does something I'm not aware of (with quotes in Discord like "tsc generally doesn't need to look at types it doesn't use").

So at this point I don't have a solution (other than `ignoreDependencies`).
